


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_Input = QtWidgets.QGroupBox(Form)
        self.gb_Input.setObjectName("gb_Input")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_Input)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_GridInput = QtWidgets.QGridLayout()
        self.layout_GridInput.setObjectName("layout_GridInput")
        self.verticalLayout_2.addLayout(self.layout_GridInput)
        self.groupBox = QtWidgets.QGroupBox(self.gb_Input)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(280, 20, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(280, 50, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(280, 80, 51, 16))
        self.label_6.setObjectName("label_6")
        self.res_input = QtWidgets.QLineEdit(self.groupBox)
        self.res_input.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.res_input.setObjectName("res_input")
        self.ind_input = QtWidgets.QLineEdit(self.groupBox)
        self.ind_input.setGeometry(QtCore.QRect(130, 50, 113, 20))
        self.ind_input.setObjectName("ind_input")
        self.curr_input = QtWidgets.QLineEdit(self.groupBox)
        self.curr_input.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.curr_input.setObjectName("curr_input")
        self.mag_input = QtWidgets.QLineEdit(self.groupBox)
        self.mag_input.setGeometry(QtCore.QRect(370, 20, 113, 20))
        self.mag_input.setObjectName("mag_input")
        self.freq_input = QtWidgets.QLineEdit(self.groupBox)
        self.freq_input.setGeometry(QtCore.QRect(370, 50, 113, 20))
        self.freq_input.setObjectName("freq_input")
        self.phase_input = QtWidgets.QLineEdit(self.groupBox)
        self.phase_input.setGeometry(QtCore.QRect(370, 80, 113, 20))
        self.phase_input.setObjectName("phase_input")
        self.cal_but = QtWidgets.QPushButton(self.groupBox)
        self.cal_but.setGeometry(QtCore.QRect(530, 20, 75, 51))
        self.cal_but.setObjectName("cal_but")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.gb_Input)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.gb_Input.setTitle(_translate("Form", "Input"))
        self.groupBox.setTitle(_translate("Form", "Input Values and Calculate"))
        self.label.setText(_translate("Form", "Resistance (Ohms)"))
        self.label_2.setText(_translate("Form", "Inductance (Faraday)"))
        self.label_3.setText(_translate("Form", "Current (Amps)"))
        self.label_4.setText(_translate("Form", "Magnitude"))
        self.label_5.setText(_translate("Form", "Frequency"))
        self.label_6.setText(_translate("Form", "Phase"))
        self.cal_but.setText(_translate("Form", "Calculate!"))
        self.groupBox_2.setTitle(_translate("Form", "Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
