

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1000, 800)
        Frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout_4 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Selector_Box = QtWidgets.QGroupBox(Frame)
        self.Selector_Box.setObjectName("Selector_Box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Selector_Box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.Selector_Box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.rdo_Otto = QtWidgets.QRadioButton(self.Selector_Box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdo_Otto.setFont(font)
        self.rdo_Otto.setObjectName("rdo_Otto")
        self.gridLayout_2.addWidget(self.rdo_Otto, 0, 1, 1, 1)
        self.rdo_Diesel = QtWidgets.QRadioButton(self.Selector_Box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdo_Diesel.setFont(font)
        self.rdo_Diesel.setObjectName("rdo_Diesel")
        self.gridLayout_2.addWidget(self.rdo_Diesel, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(674, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.Selector_Box, 0, 0, 1, 1)
        self.Pages_Widget = QtWidgets.QStackedWidget(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pages_Widget.sizePolicy().hasHeightForWidth())
        self.Pages_Widget.setSizePolicy(sizePolicy)
        self.Pages_Widget.setFrameShape(QtWidgets.QFrame.HLine)
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.Otto_page = QtWidgets.QWidget()
        self.Otto_page.setObjectName("Otto_page")
        self.gb_Input = QtWidgets.QGroupBox(self.Otto_page)
        self.gb_Input.setGeometry(QtCore.QRect(0, 1, 876, 226))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Input.sizePolicy().hasHeightForWidth())
        self.gb_Input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gb_Input.setFont(font)
        self.gb_Input.setObjectName("gb_Input")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_Input)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_Calculate = QtWidgets.QPushButton(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Calculate.sizePolicy().hasHeightForWidth())
        self.btn_Calculate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Calculate.setFont(font)
        self.btn_Calculate.setObjectName("btn_Calculate")
        self.gridLayout.addWidget(self.btn_Calculate, 0, 2, 3, 2)
        self.lbl_P0 = QtWidgets.QLabel(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_P0.sizePolicy().hasHeightForWidth())
        self.lbl_P0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_P0.setFont(font)
        self.lbl_P0.setObjectName("lbl_P0")
        self.gridLayout.addWidget(self.lbl_P0, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_TLow = QtWidgets.QLabel(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_TLow.sizePolicy().hasHeightForWidth())
        self.lbl_TLow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_TLow.setFont(font)
        self.lbl_TLow.setObjectName("lbl_TLow")
        self.gridLayout.addWidget(self.lbl_TLow, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.le_TLow = QtWidgets.QLineEdit(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_TLow.sizePolicy().hasHeightForWidth())
        self.le_TLow.setSizePolicy(sizePolicy)
        self.le_TLow.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_TLow.setFont(font)
        self.le_TLow.setClearButtonEnabled(True)
        self.le_TLow.setObjectName("le_TLow")
        self.gridLayout.addWidget(self.le_TLow, 1, 1, 1, 1)
        self.lbl_V0 = QtWidgets.QLabel(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_V0.sizePolicy().hasHeightForWidth())
        self.lbl_V0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_V0.setFont(font)
        self.lbl_V0.setObjectName("lbl_V0")
        self.gridLayout.addWidget(self.lbl_V0, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_THigh = QtWidgets.QLabel(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_THigh.sizePolicy().hasHeightForWidth())
        self.lbl_THigh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_THigh.setFont(font)
        self.lbl_THigh.setObjectName("lbl_THigh")
        self.gridLayout.addWidget(self.lbl_THigh, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 4, 1, 1)
        self.le_THigh = QtWidgets.QLineEdit(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_THigh.sizePolicy().hasHeightForWidth())
        self.le_THigh.setSizePolicy(sizePolicy)
        self.le_THigh.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_THigh.setFont(font)
        self.le_THigh.setClearButtonEnabled(True)
        self.le_THigh.setObjectName("le_THigh")
        self.gridLayout.addWidget(self.le_THigh, 0, 1, 1, 1)
        self.le_V0 = QtWidgets.QLineEdit(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_V0.sizePolicy().hasHeightForWidth())
        self.le_V0.setSizePolicy(sizePolicy)
        self.le_V0.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_V0.setFont(font)
        self.le_V0.setClearButtonEnabled(True)
        self.le_V0.setObjectName("le_V0")
        self.gridLayout.addWidget(self.le_V0, 3, 1, 1, 1)
        self.le_P0 = QtWidgets.QLineEdit(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_P0.sizePolicy().hasHeightForWidth())
        self.le_P0.setSizePolicy(sizePolicy)
        self.le_P0.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_P0.setFont(font)
        self.le_P0.setClearButtonEnabled(True)
        self.le_P0.setObjectName("le_P0")
        self.gridLayout.addWidget(self.le_P0, 2, 1, 1, 1)
        self.le_CR = QtWidgets.QLineEdit(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_CR.sizePolicy().hasHeightForWidth())
        self.le_CR.setSizePolicy(sizePolicy)
        self.le_CR.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_CR.setFont(font)
        self.le_CR.setClearButtonEnabled(True)
        self.le_CR.setObjectName("le_CR")
        self.gridLayout.addWidget(self.le_CR, 4, 1, 1, 1)
        self.lbl_CR = QtWidgets.QLabel(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_CR.sizePolicy().hasHeightForWidth())
        self.lbl_CR.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_CR.setFont(font)
        self.lbl_CR.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_CR.setObjectName("lbl_CR")
        self.gridLayout.addWidget(self.lbl_CR, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.rdo_English = QtWidgets.QRadioButton(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdo_English.sizePolicy().hasHeightForWidth())
        self.rdo_English.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdo_English.setFont(font)
        self.rdo_English.setChecked(True)
        self.rdo_English.setObjectName("rdo_English")
        self.gridLayout.addWidget(self.rdo_English, 3, 3, 1, 1)
        self.rdo_Metric = QtWidgets.QRadioButton(self.gb_Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdo_Metric.sizePolicy().hasHeightForWidth())
        self.rdo_Metric.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdo_Metric.setFont(font)
        self.rdo_Metric.setChecked(False)
        self.rdo_Metric.setObjectName("rdo_Metric")
        self.gridLayout.addWidget(self.rdo_Metric, 3, 2, 1, 1)
        self.gb_Output = QtWidgets.QGroupBox(self.Otto_page)
        self.gb_Output.setGeometry(QtCore.QRect(0, 234, 876, 189))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Output.sizePolicy().hasHeightForWidth())
        self.gb_Output.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gb_Output.setFont(font)
        self.gb_Output.setObjectName("gb_Output")
        self.grid_Output = QtWidgets.QGridLayout(self.gb_Output)
        self.grid_Output.setObjectName("grid_Output")
        self.lbl_PowerStrokeUnits = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_PowerStrokeUnits.sizePolicy().hasHeightForWidth())
        self.lbl_PowerStrokeUnits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_PowerStrokeUnits.setFont(font)
        self.lbl_PowerStrokeUnits.setObjectName("lbl_PowerStrokeUnits")
        self.grid_Output.addWidget(self.lbl_PowerStrokeUnits, 0, 5, 1, 1)
        self.le_HeatAdded = QtWidgets.QLineEdit(self.gb_Output)
        self.le_HeatAdded.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_HeatAdded.sizePolicy().hasHeightForWidth())
        self.le_HeatAdded.setSizePolicy(sizePolicy)
        self.le_HeatAdded.setMinimumSize(QtCore.QSize(0, 0))
        self.le_HeatAdded.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_HeatAdded.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_HeatAdded.setFont(font)
        self.le_HeatAdded.setObjectName("le_HeatAdded")
        self.grid_Output.addWidget(self.le_HeatAdded, 3, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.grid_Output.addWidget(self.label_12, 4, 5, 1, 1)
        self.le_T3 = QtWidgets.QLineEdit(self.gb_Output)
        self.le_T3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_T3.sizePolicy().hasHeightForWidth())
        self.le_T3.setSizePolicy(sizePolicy)
        self.le_T3.setMinimumSize(QtCore.QSize(0, 0))
        self.le_T3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_T3.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_T3.setFont(font)
        self.le_T3.setObjectName("le_T3")
        self.grid_Output.addWidget(self.le_T3, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.grid_Output.addWidget(self.label_7, 4, 0, 1, 1)
        self.le_Efficiency = QtWidgets.QLineEdit(self.gb_Output)
        self.le_Efficiency.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_Efficiency.sizePolicy().hasHeightForWidth())
        self.le_Efficiency.setSizePolicy(sizePolicy)
        self.le_Efficiency.setMinimumSize(QtCore.QSize(0, 0))
        self.le_Efficiency.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_Efficiency.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_Efficiency.setFont(font)
        self.le_Efficiency.setObjectName("le_Efficiency")
        self.grid_Output.addWidget(self.le_Efficiency, 4, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.grid_Output.addWidget(self.label_10, 4, 3, 1, 1, QtCore.Qt.AlignRight)
        self.le_T4 = QtWidgets.QLineEdit(self.gb_Output)
        self.le_T4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_T4.sizePolicy().hasHeightForWidth())
        self.le_T4.setSizePolicy(sizePolicy)
        self.le_T4.setMinimumSize(QtCore.QSize(0, 0))
        self.le_T4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_T4.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_T4.setFont(font)
        self.le_T4.setObjectName("le_T4")
        self.grid_Output.addWidget(self.le_T4, 4, 1, 1, 1)
        self.le_T1 = QtWidgets.QLineEdit(self.gb_Output)
        self.le_T1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_T1.sizePolicy().hasHeightForWidth())
        self.le_T1.setSizePolicy(sizePolicy)
        self.le_T1.setMinimumSize(QtCore.QSize(0, 0))
        self.le_T1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_T1.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_T1.setFont(font)
        self.le_T1.setObjectName("le_T1")
        self.grid_Output.addWidget(self.le_T1, 0, 1, 1, 1)
        self.le_PowerStroke = QtWidgets.QLineEdit(self.gb_Output)
        self.le_PowerStroke.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_PowerStroke.sizePolicy().hasHeightForWidth())
        self.le_PowerStroke.setSizePolicy(sizePolicy)
        self.le_PowerStroke.setMinimumSize(QtCore.QSize(0, 0))
        self.le_PowerStroke.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_PowerStroke.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_PowerStroke.setFont(font)
        self.le_PowerStroke.setObjectName("le_PowerStroke")
        self.grid_Output.addWidget(self.le_PowerStroke, 0, 4, 1, 1)
        self.lbl_T1Units = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_T1Units.sizePolicy().hasHeightForWidth())
        self.lbl_T1Units.setSizePolicy(sizePolicy)
        self.lbl_T1Units.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_T1Units.setFont(font)
        self.lbl_T1Units.setObjectName("lbl_T1Units")
        self.grid_Output.addWidget(self.lbl_T1Units, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.grid_Output.addWidget(self.label_11, 3, 3, 1, 1, QtCore.Qt.AlignRight)
        self.label_9 = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.grid_Output.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.grid_Output.addWidget(self.label_14, 0, 3, 1, 1, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.grid_Output.addWidget(self.label_2, 0, 0, 1, 1)
        self.lbl_T4Units = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_T4Units.sizePolicy().hasHeightForWidth())
        self.lbl_T4Units.setSizePolicy(sizePolicy)
        self.lbl_T4Units.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_T4Units.setFont(font)
        self.lbl_T4Units.setObjectName("lbl_T4Units")
        self.grid_Output.addWidget(self.lbl_T4Units, 4, 2, 1, 1)
        self.lbl_T3Units = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_T3Units.sizePolicy().hasHeightForWidth())
        self.lbl_T3Units.setSizePolicy(sizePolicy)
        self.lbl_T3Units.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_T3Units.setFont(font)
        self.lbl_T3Units.setObjectName("lbl_T3Units")
        self.grid_Output.addWidget(self.lbl_T3Units, 3, 2, 1, 1)
        self.le_T2 = QtWidgets.QLineEdit(self.gb_Output)
        self.le_T2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_T2.sizePolicy().hasHeightForWidth())
        self.le_T2.setSizePolicy(sizePolicy)
        self.le_T2.setMinimumSize(QtCore.QSize(0, 0))
        self.le_T2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_T2.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_T2.setFont(font)
        self.le_T2.setObjectName("le_T2")
        self.grid_Output.addWidget(self.le_T2, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.grid_Output.addWidget(self.label_5, 2, 0, 1, 1)
        self.le_CompressionStroke = QtWidgets.QLineEdit(self.gb_Output)
        self.le_CompressionStroke.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_CompressionStroke.sizePolicy().hasHeightForWidth())
        self.le_CompressionStroke.setSizePolicy(sizePolicy)
        self.le_CompressionStroke.setMinimumSize(QtCore.QSize(0, 0))
        self.le_CompressionStroke.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_CompressionStroke.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_CompressionStroke.setFont(font)
        self.le_CompressionStroke.setObjectName("le_CompressionStroke")
        self.grid_Output.addWidget(self.le_CompressionStroke, 2, 4, 1, 1)
        self.lbl_HeatInUnits = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_HeatInUnits.sizePolicy().hasHeightForWidth())
        self.lbl_HeatInUnits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_HeatInUnits.setFont(font)
        self.lbl_HeatInUnits.setObjectName("lbl_HeatInUnits")
        self.grid_Output.addWidget(self.lbl_HeatInUnits, 3, 5, 1, 1)
        self.lbl_CompressionStrokeUnits = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_CompressionStrokeUnits.sizePolicy().hasHeightForWidth())
        self.lbl_CompressionStrokeUnits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_CompressionStrokeUnits.setFont(font)
        self.lbl_CompressionStrokeUnits.setObjectName("lbl_CompressionStrokeUnits")
        self.grid_Output.addWidget(self.lbl_CompressionStrokeUnits, 2, 5, 1, 1)
        self.lbl_T2Units = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_T2Units.sizePolicy().hasHeightForWidth())
        self.lbl_T2Units.setSizePolicy(sizePolicy)
        self.lbl_T2Units.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_T2Units.setFont(font)
        self.lbl_T2Units.setObjectName("lbl_T2Units")
        self.grid_Output.addWidget(self.lbl_T2Units, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gb_Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.grid_Output.addWidget(self.label_15, 2, 3, 1, 1, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_Output.addItem(spacerItem2, 3, 6, 1, 1)
        self.gb_Plot = QtWidgets.QGroupBox(self.Otto_page)
        self.gb_Plot.setGeometry(QtCore.QRect(0, 430, 881, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Plot.sizePolicy().hasHeightForWidth())
        self.gb_Plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gb_Plot.setFont(font)
        self.gb_Plot.setObjectName("gb_Plot")
        self.grid_Plot = QtWidgets.QGridLayout(self.gb_Plot)
        self.grid_Plot.setObjectName("grid_Plot")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_Plot.addItem(spacerItem3, 0, 4, 1, 1)
        self.cmb_Ordinate = QtWidgets.QComboBox(self.gb_Plot)
        self.cmb_Ordinate.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cmb_Ordinate.setObjectName("cmb_Ordinate")
        self.cmb_Ordinate.addItem("")
        self.cmb_Ordinate.addItem("")
        self.cmb_Ordinate.addItem("")
        self.cmb_Ordinate.addItem("")
        self.cmb_Ordinate.addItem("")
        self.cmb_Ordinate.addItem("")
        self.grid_Plot.addWidget(self.cmb_Ordinate, 0, 3, 1, 1)
        self.lbl_Abcissa = QtWidgets.QLabel(self.gb_Plot)
        self.lbl_Abcissa.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lbl_Abcissa.setObjectName("lbl_Abcissa")
        self.grid_Plot.addWidget(self.lbl_Abcissa, 0, 0, 1, 1)
        self.lbl_Ordinate = QtWidgets.QLabel(self.gb_Plot)
        self.lbl_Ordinate.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lbl_Ordinate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Ordinate.setObjectName("lbl_Ordinate")
        self.grid_Plot.addWidget(self.lbl_Ordinate, 0, 2, 1, 1)
        self.chk_LogAbcissa = QtWidgets.QCheckBox(self.gb_Plot)
        self.chk_LogAbcissa.setObjectName("chk_LogAbcissa")
        self.grid_Plot.addWidget(self.chk_LogAbcissa, 1, 0, 1, 2)
        self.chk_LogOrdinate = QtWidgets.QCheckBox(self.gb_Plot)
        self.chk_LogOrdinate.setObjectName("chk_LogOrdinate")
        self.grid_Plot.addWidget(self.chk_LogOrdinate, 1, 2, 1, 2)
        self.cmb_Abcissa = QtWidgets.QComboBox(self.gb_Plot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_Abcissa.sizePolicy().hasHeightForWidth())
        self.cmb_Abcissa.setSizePolicy(sizePolicy)
        self.cmb_Abcissa.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cmb_Abcissa.setObjectName("cmb_Abcissa")
        self.cmb_Abcissa.addItem("")
        self.cmb_Abcissa.addItem("")
        self.cmb_Abcissa.addItem("")
        self.cmb_Abcissa.addItem("")
        self.cmb_Abcissa.addItem("")
        self.cmb_Abcissa.addItem("")
        self.grid_Plot.addWidget(self.cmb_Abcissa, 0, 1, 1, 1)
        self.Pages_Widget.addWidget(self.Otto_page)
        self.Diesel_page = QtWidgets.QWidget()
        self.Diesel_page.setObjectName("Diesel_page")
        self.gb_Input_2 = QtWidgets.QGroupBox(self.Diesel_page)
        self.gb_Input_2.setGeometry(QtCore.QRect(0, 11, 876, 226))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Input_2.sizePolicy().hasHeightForWidth())
        self.gb_Input_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gb_Input_2.setFont(font)
        self.gb_Input_2.setObjectName("gb_Input_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gb_Input_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rdo_Metric_3 = QtWidgets.QRadioButton(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdo_Metric_3.sizePolicy().hasHeightForWidth())
        self.rdo_Metric_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdo_Metric_3.setFont(font)
        self.rdo_Metric_3.setChecked(False)
        self.rdo_Metric_3.setObjectName("rdo_Metric_3")
        self.gridLayout_3.addWidget(self.rdo_Metric_3, 2, 2, 1, 1)
        self.rdo_English_3 = QtWidgets.QRadioButton(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdo_English_3.sizePolicy().hasHeightForWidth())
        self.rdo_English_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdo_English_3.setFont(font)
        self.rdo_English_3.setChecked(True)
        self.rdo_English_3.setObjectName("rdo_English_3")
        self.gridLayout_3.addWidget(self.rdo_English_3, 2, 3, 1, 1)
        self.lbl_CR_3 = QtWidgets.QLabel(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_CR_3.sizePolicy().hasHeightForWidth())
        self.lbl_CR_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_CR_3.setFont(font)
        self.lbl_CR_3.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_CR_3.setObjectName("lbl_CR_3")
        self.gridLayout_3.addWidget(self.lbl_CR_3, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.le_V0_3 = QtWidgets.QLineEdit(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_V0_3.sizePolicy().hasHeightForWidth())
        self.le_V0_3.setSizePolicy(sizePolicy)
        self.le_V0_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_V0_3.setFont(font)
        self.le_V0_3.setClearButtonEnabled(True)
        self.le_V0_3.setObjectName("le_V0_3")
        self.gridLayout_3.addWidget(self.le_V0_3, 2, 1, 1, 1)
        self.le_P0_3 = QtWidgets.QLineEdit(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_P0_3.sizePolicy().hasHeightForWidth())
        self.le_P0_3.setSizePolicy(sizePolicy)
        self.le_P0_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_P0_3.setFont(font)
        self.le_P0_3.setClearButtonEnabled(True)
        self.le_P0_3.setObjectName("le_P0_3")
        self.gridLayout_3.addWidget(self.le_P0_3, 1, 1, 1, 1)
        self.le_CR_3 = QtWidgets.QLineEdit(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_CR_3.sizePolicy().hasHeightForWidth())
        self.le_CR_3.setSizePolicy(sizePolicy)
        self.le_CR_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_CR_3.setFont(font)
        self.le_CR_3.setClearButtonEnabled(True)
        self.le_CR_3.setObjectName("le_CR_3")
        self.gridLayout_3.addWidget(self.le_CR_3, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 2, 4, 1, 1)
        self.le_THigh_3 = QtWidgets.QLineEdit(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_THigh_3.sizePolicy().hasHeightForWidth())
        self.le_THigh_3.setSizePolicy(sizePolicy)
        self.le_THigh_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_THigh_3.setFont(font)
        self.le_THigh_3.setClearButtonEnabled(True)
        self.le_THigh_3.setObjectName("le_THigh_3")
        self.gridLayout_3.addWidget(self.le_THigh_3, 0, 1, 1, 1)
        self.btn_Calculate_3 = QtWidgets.QPushButton(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Calculate_3.sizePolicy().hasHeightForWidth())
        self.btn_Calculate_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Calculate_3.setFont(font)
        self.btn_Calculate_3.setObjectName("btn_Calculate_3")
        self.gridLayout_3.addWidget(self.btn_Calculate_3, 0, 2, 2, 2)
        self.lbl_P0_3 = QtWidgets.QLabel(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_P0_3.sizePolicy().hasHeightForWidth())
        self.lbl_P0_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_P0_3.setFont(font)
        self.lbl_P0_3.setObjectName("lbl_P0_3")
        self.gridLayout_3.addWidget(self.lbl_P0_3, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_V0_3 = QtWidgets.QLabel(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_V0_3.sizePolicy().hasHeightForWidth())
        self.lbl_V0_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_V0_3.setFont(font)
        self.lbl_V0_3.setObjectName("lbl_V0_3")
        self.gridLayout_3.addWidget(self.lbl_V0_3, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_THigh_3 = QtWidgets.QLabel(self.gb_Input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_THigh_3.sizePolicy().hasHeightForWidth())
        self.lbl_THigh_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_THigh_3.setFont(font)
        self.lbl_THigh_3.setObjectName("lbl_THigh_3")
        self.gridLayout_3.addWidget(self.lbl_THigh_3, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gb_Output_2 = QtWidgets.QGroupBox(self.Diesel_page)
        self.gb_Output_2.setGeometry(QtCore.QRect(0, 244, 876, 189))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Output_2.sizePolicy().hasHeightForWidth())
        self.gb_Output_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gb_Output_2.setFont(font)
        self.gb_Output_2.setObjectName("gb_Output_2")
        self.grid_Output_3 = QtWidgets.QGridLayout(self.gb_Output_2)
        self.grid_Output_3.setObjectName("grid_Output_3")
        self.lbl_PowerStrokeUnits_3 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_PowerStrokeUnits_3.sizePolicy().hasHeightForWidth())
        self.lbl_PowerStrokeUnits_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_PowerStrokeUnits_3.setFont(font)
        self.lbl_PowerStrokeUnits_3.setObjectName("lbl_PowerStrokeUnits_3")
        self.grid_Output_3.addWidget(self.lbl_PowerStrokeUnits_3, 0, 5, 1, 1)
        self.le_HeatAdded_3 = QtWidgets.QLineEdit(self.gb_Output_2)
        self.le_HeatAdded_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_HeatAdded_3.sizePolicy().hasHeightForWidth())
        self.le_HeatAdded_3.setSizePolicy(sizePolicy)
        self.le_HeatAdded_3.setMinimumSize(QtCore.QSize(0, 0))
        self.le_HeatAdded_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_HeatAdded_3.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_HeatAdded_3.setFont(font)
        self.le_HeatAdded_3.setObjectName("le_HeatAdded_3")
        self.grid_Output_3.addWidget(self.le_HeatAdded_3, 3, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.grid_Output_3.addWidget(self.label_21, 4, 5, 1, 1)
        self.le_T3_3 = QtWidgets.QLineEdit(self.gb_Output_2)
        self.le_T3_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_T3_3.sizePolicy().hasHeightForWidth())
        self.le_T3_3.setSizePolicy(sizePolicy)
        self.le_T3_3.setMinimumSize(QtCore.QSize(0, 0))
        self.le_T3_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_T3_3.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_T3_3.setFont(font)
        self.le_T3_3.setObjectName("le_T3_3")
        self.grid_Output_3.addWidget(self.le_T3_3, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.grid_Output_3.addWidget(self.label_22, 4, 0, 1, 1)
        self.le_Efficiency_3 = QtWidgets.QLineEdit(self.gb_Output_2)
        self.le_Efficiency_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_Efficiency_3.sizePolicy().hasHeightForWidth())
        self.le_Efficiency_3.setSizePolicy(sizePolicy)
        self.le_Efficiency_3.setMinimumSize(QtCore.QSize(0, 0))
        self.le_Efficiency_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_Efficiency_3.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_Efficiency_3.setFont(font)
        self.le_Efficiency_3.setObjectName("le_Efficiency_3")
        self.grid_Output_3.addWidget(self.le_Efficiency_3, 4, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.grid_Output_3.addWidget(self.label_23, 4, 3, 1, 1, QtCore.Qt.AlignRight)
        self.le_T4_3 = QtWidgets.QLineEdit(self.gb_Output_2)
        self.le_T4_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_T4_3.sizePolicy().hasHeightForWidth())
        self.le_T4_3.setSizePolicy(sizePolicy)
        self.le_T4_3.setMinimumSize(QtCore.QSize(0, 0))
        self.le_T4_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_T4_3.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_T4_3.setFont(font)
        self.le_T4_3.setObjectName("le_T4_3")
        self.grid_Output_3.addWidget(self.le_T4_3, 4, 1, 1, 1)
        self.le_T1_3 = QtWidgets.QLineEdit(self.gb_Output_2)
        self.le_T1_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_T1_3.sizePolicy().hasHeightForWidth())
        self.le_T1_3.setSizePolicy(sizePolicy)
        self.le_T1_3.setMinimumSize(QtCore.QSize(0, 0))
        self.le_T1_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_T1_3.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_T1_3.setFont(font)
        self.le_T1_3.setObjectName("le_T1_3")
        self.grid_Output_3.addWidget(self.le_T1_3, 0, 1, 1, 1)
        self.le_PowerStroke_3 = QtWidgets.QLineEdit(self.gb_Output_2)
        self.le_PowerStroke_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_PowerStroke_3.sizePolicy().hasHeightForWidth())
        self.le_PowerStroke_3.setSizePolicy(sizePolicy)
        self.le_PowerStroke_3.setMinimumSize(QtCore.QSize(0, 0))
        self.le_PowerStroke_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_PowerStroke_3.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_PowerStroke_3.setFont(font)
        self.le_PowerStroke_3.setObjectName("le_PowerStroke_3")
        self.grid_Output_3.addWidget(self.le_PowerStroke_3, 0, 4, 1, 1)
        self.lbl_T1Units_3 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_T1Units_3.sizePolicy().hasHeightForWidth())
        self.lbl_T1Units_3.setSizePolicy(sizePolicy)
        self.lbl_T1Units_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_T1Units_3.setFont(font)
        self.lbl_T1Units_3.setObjectName("lbl_T1Units_3")
        self.grid_Output_3.addWidget(self.lbl_T1Units_3, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.grid_Output_3.addWidget(self.label_24, 3, 3, 1, 1, QtCore.Qt.AlignRight)
        self.label_25 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.grid_Output_3.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.grid_Output_3.addWidget(self.label_26, 0, 3, 1, 1, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.grid_Output_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.lbl_T4Units_3 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_T4Units_3.sizePolicy().hasHeightForWidth())
        self.lbl_T4Units_3.setSizePolicy(sizePolicy)
        self.lbl_T4Units_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_T4Units_3.setFont(font)
        self.lbl_T4Units_3.setObjectName("lbl_T4Units_3")
        self.grid_Output_3.addWidget(self.lbl_T4Units_3, 4, 2, 1, 1)
        self.lbl_T3Units_3 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_T3Units_3.sizePolicy().hasHeightForWidth())
        self.lbl_T3Units_3.setSizePolicy(sizePolicy)
        self.lbl_T3Units_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_T3Units_3.setFont(font)
        self.lbl_T3Units_3.setObjectName("lbl_T3Units_3")
        self.grid_Output_3.addWidget(self.lbl_T3Units_3, 3, 2, 1, 1)
        self.le_T2_3 = QtWidgets.QLineEdit(self.gb_Output_2)
        self.le_T2_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_T2_3.sizePolicy().hasHeightForWidth())
        self.le_T2_3.setSizePolicy(sizePolicy)
        self.le_T2_3.setMinimumSize(QtCore.QSize(0, 0))
        self.le_T2_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_T2_3.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_T2_3.setFont(font)
        self.le_T2_3.setObjectName("le_T2_3")
        self.grid_Output_3.addWidget(self.le_T2_3, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.grid_Output_3.addWidget(self.label_27, 2, 0, 1, 1)
        self.le_CompressionStroke_3 = QtWidgets.QLineEdit(self.gb_Output_2)
        self.le_CompressionStroke_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_CompressionStroke_3.sizePolicy().hasHeightForWidth())
        self.le_CompressionStroke_3.setSizePolicy(sizePolicy)
        self.le_CompressionStroke_3.setMinimumSize(QtCore.QSize(0, 0))
        self.le_CompressionStroke_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_CompressionStroke_3.setBaseSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_CompressionStroke_3.setFont(font)
        self.le_CompressionStroke_3.setObjectName("le_CompressionStroke_3")
        self.grid_Output_3.addWidget(self.le_CompressionStroke_3, 2, 4, 1, 1)
        self.lbl_HeatInUnits_3 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_HeatInUnits_3.sizePolicy().hasHeightForWidth())
        self.lbl_HeatInUnits_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_HeatInUnits_3.setFont(font)
        self.lbl_HeatInUnits_3.setObjectName("lbl_HeatInUnits_3")
        self.grid_Output_3.addWidget(self.lbl_HeatInUnits_3, 3, 5, 1, 1)
        self.lbl_CompressionStrokeUnits_3 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_CompressionStrokeUnits_3.sizePolicy().hasHeightForWidth())
        self.lbl_CompressionStrokeUnits_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_CompressionStrokeUnits_3.setFont(font)
        self.lbl_CompressionStrokeUnits_3.setObjectName("lbl_CompressionStrokeUnits_3")
        self.grid_Output_3.addWidget(self.lbl_CompressionStrokeUnits_3, 2, 5, 1, 1)
        self.lbl_T2Units_3 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_T2Units_3.sizePolicy().hasHeightForWidth())
        self.lbl_T2Units_3.setSizePolicy(sizePolicy)
        self.lbl_T2Units_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_T2Units_3.setFont(font)
        self.lbl_T2Units_3.setObjectName("lbl_T2Units_3")
        self.grid_Output_3.addWidget(self.lbl_T2Units_3, 2, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gb_Output_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.grid_Output_3.addWidget(self.label_28, 2, 3, 1, 1, QtCore.Qt.AlignRight)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_Output_3.addItem(spacerItem5, 3, 6, 1, 1)
        self.gb_Plot_2 = QtWidgets.QGroupBox(self.Diesel_page)
        self.gb_Plot_2.setGeometry(QtCore.QRect(0, 440, 881, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Plot_2.sizePolicy().hasHeightForWidth())
        self.gb_Plot_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gb_Plot_2.setFont(font)
        self.gb_Plot_2.setObjectName("gb_Plot_2")
        self.grid_Plot_3 = QtWidgets.QGridLayout(self.gb_Plot_2)
        self.grid_Plot_3.setObjectName("grid_Plot_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_Plot_3.addItem(spacerItem6, 0, 4, 1, 1)
        self.cmb_Ordinate_3 = QtWidgets.QComboBox(self.gb_Plot_2)
        self.cmb_Ordinate_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cmb_Ordinate_3.setObjectName("cmb_Ordinate_3")
        self.cmb_Ordinate_3.addItem("")
        self.cmb_Ordinate_3.addItem("")
        self.cmb_Ordinate_3.addItem("")
        self.cmb_Ordinate_3.addItem("")
        self.cmb_Ordinate_3.addItem("")
        self.cmb_Ordinate_3.addItem("")
        self.grid_Plot_3.addWidget(self.cmb_Ordinate_3, 0, 3, 1, 1)
        self.lbl_Abcissa_3 = QtWidgets.QLabel(self.gb_Plot_2)
        self.lbl_Abcissa_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lbl_Abcissa_3.setObjectName("lbl_Abcissa_3")
        self.grid_Plot_3.addWidget(self.lbl_Abcissa_3, 0, 0, 1, 1)
        self.lbl_Ordinate_3 = QtWidgets.QLabel(self.gb_Plot_2)
        self.lbl_Ordinate_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lbl_Ordinate_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Ordinate_3.setObjectName("lbl_Ordinate_3")
        self.grid_Plot_3.addWidget(self.lbl_Ordinate_3, 0, 2, 1, 1)
        self.chk_LogAbcissa_3 = QtWidgets.QCheckBox(self.gb_Plot_2)
        self.chk_LogAbcissa_3.setObjectName("chk_LogAbcissa_3")
        self.grid_Plot_3.addWidget(self.chk_LogAbcissa_3, 1, 0, 1, 2)
        self.chk_LogOrdinate_3 = QtWidgets.QCheckBox(self.gb_Plot_2)
        self.chk_LogOrdinate_3.setObjectName("chk_LogOrdinate_3")
        self.grid_Plot_3.addWidget(self.chk_LogOrdinate_3, 1, 2, 1, 2)
        self.cmb_Abcissa_3 = QtWidgets.QComboBox(self.gb_Plot_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_Abcissa_3.sizePolicy().hasHeightForWidth())
        self.cmb_Abcissa_3.setSizePolicy(sizePolicy)
        self.cmb_Abcissa_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cmb_Abcissa_3.setObjectName("cmb_Abcissa_3")
        self.cmb_Abcissa_3.addItem("")
        self.cmb_Abcissa_3.addItem("")
        self.cmb_Abcissa_3.addItem("")
        self.cmb_Abcissa_3.addItem("")
        self.cmb_Abcissa_3.addItem("")
        self.cmb_Abcissa_3.addItem("")
        self.grid_Plot_3.addWidget(self.cmb_Abcissa_3, 0, 1, 1, 1)
        self.Pages_Widget.addWidget(self.Diesel_page)
        self.gridLayout_4.addWidget(self.Pages_Widget, 1, 0, 1, 1)

        self.retranslateUi(Frame)
        self.Pages_Widget.setCurrentIndex(1)
        self.cmb_Ordinate.setCurrentIndex(0)
        self.cmb_Abcissa.setCurrentIndex(5)
        self.cmb_Ordinate_3.setCurrentIndex(0)
        self.cmb_Abcissa_3.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Thermodynamics"))
        self.Selector_Box.setTitle(_translate("Frame", "GroupBox"))
        self.label.setText(_translate("Frame", "Select Cycle:"))
        self.rdo_Otto.setText(_translate("Frame", "Otto Cycle"))
        self.rdo_Diesel.setText(_translate("Frame", "Diesel Cycle"))
        self.gb_Input.setTitle(_translate("Frame", "Input for Air Standard Otto Cycle"))
        self.btn_Calculate.setText(_translate("Frame", "Calculate"))
        self.lbl_P0.setText(_translate("Frame", "P0 (atm)"))
        self.lbl_TLow.setText(_translate("Frame", "T Low (R)"))
        self.le_TLow.setText(_translate("Frame", "500.0"))
        self.le_TLow.setPlaceholderText(_translate("Frame", "enter a value for the high pressure isobar"))
        self.lbl_V0.setText(_translate("Frame", "Cylinder V (ft^3)"))
        self.lbl_THigh.setText(_translate("Frame", "T High (R)"))
        self.le_THigh.setText(_translate("Frame", "3600.0"))
        self.le_THigh.setPlaceholderText(_translate("Frame", "enter a value for the high pressure isobar"))
        self.le_V0.setText(_translate("Frame", "0.02"))
        self.le_P0.setText(_translate("Frame", "1.0"))
        self.le_P0.setPlaceholderText(_translate("Frame", "enter a value for the low pressure isobar"))
        self.le_CR.setText(_translate("Frame", "8.0"))
        self.le_CR.setPlaceholderText(_translate("Frame", "turbine isentropic efficiency 0.0<eta<=1.0"))
        self.lbl_CR.setText(_translate("Frame", "Compression Ratio"))
        self.rdo_English.setText(_translate("Frame", "English"))
        self.rdo_Metric.setText(_translate("Frame", "Metric"))
        self.gb_Output.setTitle(_translate("Frame", "Output"))
        self.lbl_PowerStrokeUnits.setText(_translate("Frame", "kJ/kg"))
        self.label_12.setText(_translate("Frame", "%"))
        self.label_7.setText(_translate("Frame", "T4"))
        self.label_10.setText(_translate("Frame", "Cycle Efficiency"))
        self.lbl_T1Units.setText(_translate("Frame", "C"))
        self.label_11.setText(_translate("Frame", "Heat Added"))
        self.label_9.setText(_translate("Frame", "T3"))
        self.label_14.setText(_translate("Frame", "Power Stroke"))
        self.label_2.setText(_translate("Frame", "T1"))
        self.lbl_T4Units.setText(_translate("Frame", "C"))
        self.lbl_T3Units.setText(_translate("Frame", "C"))
        self.label_5.setText(_translate("Frame", "T2"))
        self.lbl_HeatInUnits.setText(_translate("Frame", "kJ/kg"))
        self.lbl_CompressionStrokeUnits.setText(_translate("Frame", "kJ/kg"))
        self.lbl_T2Units.setText(_translate("Frame", "C"))
        self.label_15.setText(_translate("Frame", "Compression Stroke"))
        self.gb_Plot.setTitle(_translate("Frame", "Plot"))
        self.cmb_Ordinate.setItemText(0, _translate("Frame", "P"))
        self.cmb_Ordinate.setItemText(1, _translate("Frame", "T"))
        self.cmb_Ordinate.setItemText(2, _translate("Frame", "u"))
        self.cmb_Ordinate.setItemText(3, _translate("Frame", "h"))
        self.cmb_Ordinate.setItemText(4, _translate("Frame", "s"))
        self.cmb_Ordinate.setItemText(5, _translate("Frame", "v"))
        self.lbl_Abcissa.setText(_translate("Frame", "Abcissa (x)"))
        self.lbl_Ordinate.setText(_translate("Frame", "Ordinate (y)"))
        self.chk_LogAbcissa.setText(_translate("Frame", "Logarithmic (x)"))
        self.chk_LogOrdinate.setText(_translate("Frame", "Logarithmic (y)"))
        self.cmb_Abcissa.setCurrentText(_translate("Frame", "v"))
        self.cmb_Abcissa.setItemText(0, _translate("Frame", "P"))
        self.cmb_Abcissa.setItemText(1, _translate("Frame", "T"))
        self.cmb_Abcissa.setItemText(2, _translate("Frame", "u"))
        self.cmb_Abcissa.setItemText(3, _translate("Frame", "h"))
        self.cmb_Abcissa.setItemText(4, _translate("Frame", "s"))
        self.cmb_Abcissa.setItemText(5, _translate("Frame", "v"))
        self.gb_Input_2.setTitle(_translate("Frame", "Input for Air Standard Diesel Cycle"))
        self.rdo_Metric_3.setText(_translate("Frame", "Metric"))
        self.rdo_English_3.setText(_translate("Frame", "English"))
        self.lbl_CR_3.setText(_translate("Frame", "Compression Ratio"))
        self.le_V0_3.setText(_translate("Frame", "0.02"))
        self.le_P0_3.setText(_translate("Frame", "1.0"))
        self.le_P0_3.setPlaceholderText(_translate("Frame", "enter a value for the low pressure isobar"))
        self.le_CR_3.setText(_translate("Frame", "8.0"))
        self.le_CR_3.setPlaceholderText(_translate("Frame", "turbine isentropic efficiency 0.0<eta<=1.0"))
        self.le_THigh_3.setText(_translate("Frame", "3600.0"))
        self.le_THigh_3.setPlaceholderText(_translate("Frame", "enter a value for the high pressure isobar"))
        self.btn_Calculate_3.setText(_translate("Frame", "Calculate"))
        self.lbl_P0_3.setText(_translate("Frame", "P 1 (atm)"))
        self.lbl_V0_3.setText(_translate("Frame", "Cutoff Ratio"))
        self.lbl_THigh_3.setText(_translate("Frame", "T 1 (R)"))
        self.gb_Output_2.setTitle(_translate("Frame", "Output"))
        self.lbl_PowerStrokeUnits_3.setText(_translate("Frame", "kJ/kg"))
        self.label_21.setText(_translate("Frame", "%"))
        self.label_22.setText(_translate("Frame", "T4"))
        self.label_23.setText(_translate("Frame", "Cycle Efficiency"))
        self.lbl_T1Units_3.setText(_translate("Frame", "C"))
        self.label_24.setText(_translate("Frame", "Heat Added"))
        self.label_25.setText(_translate("Frame", "T3"))
        self.label_26.setText(_translate("Frame", "Power Stroke"))
        self.label_4.setText(_translate("Frame", "T1"))
        self.lbl_T4Units_3.setText(_translate("Frame", "C"))
        self.lbl_T3Units_3.setText(_translate("Frame", "C"))
        self.label_27.setText(_translate("Frame", "T2"))
        self.lbl_HeatInUnits_3.setText(_translate("Frame", "kJ/kg"))
        self.lbl_CompressionStrokeUnits_3.setText(_translate("Frame", "kJ/kg"))
        self.lbl_T2Units_3.setText(_translate("Frame", "C"))
        self.label_28.setText(_translate("Frame", "Compression Stroke"))
        self.gb_Plot_2.setTitle(_translate("Frame", "Plot"))
        self.cmb_Ordinate_3.setItemText(0, _translate("Frame", "P"))
        self.cmb_Ordinate_3.setItemText(1, _translate("Frame", "T"))
        self.cmb_Ordinate_3.setItemText(2, _translate("Frame", "u"))
        self.cmb_Ordinate_3.setItemText(3, _translate("Frame", "h"))
        self.cmb_Ordinate_3.setItemText(4, _translate("Frame", "s"))
        self.cmb_Ordinate_3.setItemText(5, _translate("Frame", "v"))
        self.lbl_Abcissa_3.setText(_translate("Frame", "Abcissa (x)"))
        self.lbl_Ordinate_3.setText(_translate("Frame", "Ordinate (y)"))
        self.chk_LogAbcissa_3.setText(_translate("Frame", "Logarithmic (x)"))
        self.chk_LogOrdinate_3.setText(_translate("Frame", "Logarithmic (y)"))
        self.cmb_Abcissa_3.setCurrentText(_translate("Frame", "v"))
        self.cmb_Abcissa_3.setItemText(0, _translate("Frame", "P"))
        self.cmb_Abcissa_3.setItemText(1, _translate("Frame", "T"))
        self.cmb_Abcissa_3.setItemText(2, _translate("Frame", "u"))
        self.cmb_Abcissa_3.setItemText(3, _translate("Frame", "h"))
        self.cmb_Abcissa_3.setItemText(4, _translate("Frame", "s"))
        self.cmb_Abcissa_3.setItemText(5, _translate("Frame", "v"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
